[package]
name = "conduit-wasm"
version = "0.1.0"
authors = ["Jet Li <jing.i.qin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.9.2"
yew-router = "0.6.1"